/**
 * Região de cada município de Mato Grosso, na divisão regional do IBGE.
 *
 * GERADO POR `node scripts/gerar-regioes.mjs` — não edite à mão.
 * Fonte: API de localidades do IBGE. Gerado em 2026-08-26.
 *
 * 142 municípios, 18 regiões imediatas,
 * 5 intermediárias.
 *
 * A região imediata agrupa municípios pelo deslocamento real das pessoas
 * para bens e serviços — é o que faz dela uma medida de "perto" melhor que
 * a distância em linha reta, num estado onde a estrada decide o tempo de
 * viagem. Quem consome isto é `src/lib/proximidade.ts`.
 */

/** cidade → [região imediata, região intermediária] */
export const REGIOES_MT: Record<string, readonly [string, string]> = {
  Acorizal: ["Cuiabá", "Cuiabá"],
  "Água Boa": ["Água Boa", "Barra do Garças"],
  "Alta Floresta": ["Alta Floresta", "Sinop"],
  "Alto Araguaia": ["Rondonópolis", "Rondonópolis"],
  "Alto Boa Vista": ["Confresa - Vila Rica", "Barra do Garças"],
  "Alto Garças": ["Rondonópolis", "Rondonópolis"],
  "Alto Paraguai": ["Diamantino", "Cuiabá"],
  "Alto Taquari": ["Rondonópolis", "Rondonópolis"],
  Apiacás: ["Alta Floresta", "Sinop"],
  Araguaiana: ["Barra do Garças", "Barra do Garças"],
  Araguainha: ["Rondonópolis", "Rondonópolis"],
  Araputanga: ["Mirassol D'oeste", "Cáceres"],
  Arenápolis: ["Diamantino", "Cuiabá"],
  Aripuanã: ["Juína", "Sinop"],
  "Barão de Melgaço": ["Cuiabá", "Cuiabá"],
  "Barra do Bugres": ["Tangará da Serra", "Cuiabá"],
  "Barra do Garças": ["Barra do Garças", "Barra do Garças"],
  "Boa Esperança do Norte": ["Sorriso", "Sinop"],
  "Bom Jesus do Araguaia": ["Confresa - Vila Rica", "Barra do Garças"],
  Brasnorte: ["Tangará da Serra", "Cuiabá"],
  Cáceres: ["Cáceres", "Cáceres"],
  Campinápolis: ["Água Boa", "Barra do Garças"],
  "Campo Novo do Parecis": ["Tangará da Serra", "Cuiabá"],
  "Campo Verde": ["Cuiabá", "Cuiabá"],
  "Campos de Júlio": ["Pontes e Lacerda - Comodoro", "Cáceres"],
  "Canabrava do Norte": ["Confresa - Vila Rica", "Barra do Garças"],
  Canarana: ["Água Boa", "Barra do Garças"],
  Carlinda: ["Alta Floresta", "Sinop"],
  Castanheira: ["Juína", "Sinop"],
  "Chapada dos Guimarães": ["Cuiabá", "Cuiabá"],
  Cláudia: ["Sinop", "Sinop"],
  Cocalinho: ["Água Boa", "Barra do Garças"],
  Colíder: ["Sinop", "Sinop"],
  Colniza: ["Juína", "Sinop"],
  Comodoro: ["Pontes e Lacerda - Comodoro", "Cáceres"],
  Confresa: ["Confresa - Vila Rica", "Barra do Garças"],
  "Conquista D'Oeste": ["Pontes e Lacerda - Comodoro", "Cáceres"],
  Cotriguaçu: ["Juína", "Sinop"],
  Cuiabá: ["Cuiabá", "Cuiabá"],
  Curvelândia: ["Cáceres", "Cáceres"],
  Denise: ["Tangará da Serra", "Cuiabá"],
  Diamantino: ["Diamantino", "Cuiabá"],
  "Dom Aquino": ["Jaciara", "Rondonópolis"],
  "Feliz Natal": ["Sinop", "Sinop"],
  "Figueirópolis D'Oeste": ["Mirassol D'oeste", "Cáceres"],
  "Gaúcha do Norte": ["Água Boa", "Barra do Garças"],
  "General Carneiro": ["Barra do Garças", "Barra do Garças"],
  "Glória D'Oeste": ["Mirassol D'oeste", "Cáceres"],
  "Guarantã do Norte": ["Peixoto de Azevedo - Guarantã do Norte", "Sinop"],
  Guiratinga: ["Rondonópolis", "Rondonópolis"],
  Indiavaí: ["Mirassol D'oeste", "Cáceres"],
  "Ipiranga do Norte": ["Sorriso", "Sinop"],
  Itanhangá: ["Sorriso", "Sinop"],
  Itaúba: ["Sinop", "Sinop"],
  Itiquira: ["Rondonópolis", "Rondonópolis"],
  Jaciara: ["Jaciara", "Rondonópolis"],
  Jangada: ["Cuiabá", "Cuiabá"],
  Jauru: ["Mirassol D'oeste", "Cáceres"],
  Juara: ["Juara", "Sinop"],
  Juína: ["Juína", "Sinop"],
  Juruena: ["Juína", "Sinop"],
  Juscimeira: ["Jaciara", "Rondonópolis"],
  "Lambari D'Oeste": ["Cáceres", "Cáceres"],
  "Lucas do Rio Verde": ["Sorriso", "Sinop"],
  Luciara: ["Confresa - Vila Rica", "Barra do Garças"],
  Marcelândia: ["Sinop", "Sinop"],
  Matupá: ["Peixoto de Azevedo - Guarantã do Norte", "Sinop"],
  "Mirassol d'Oeste": ["Mirassol D'oeste", "Cáceres"],
  Nobres: ["Cuiabá", "Cuiabá"],
  Nortelândia: ["Diamantino", "Cuiabá"],
  "Nossa Senhora do Livramento": ["Cuiabá", "Cuiabá"],
  "Nova Bandeirantes": ["Alta Floresta", "Sinop"],
  "Nova Brasilândia": ["Cuiabá", "Cuiabá"],
  "Nova Canaã do Norte": ["Sinop", "Sinop"],
  "Nova Guarita": ["Sinop", "Sinop"],
  "Nova Lacerda": ["Pontes e Lacerda - Comodoro", "Cáceres"],
  "Nova Marilândia": ["Diamantino", "Cuiabá"],
  "Nova Maringá": ["Diamantino", "Cuiabá"],
  "Nova Monte Verde": ["Alta Floresta", "Sinop"],
  "Nova Mutum": ["Sorriso", "Sinop"],
  "Nova Nazaré": ["Água Boa", "Barra do Garças"],
  "Nova Olímpia": ["Tangará da Serra", "Cuiabá"],
  "Nova Santa Helena": ["Sinop", "Sinop"],
  "Nova Ubiratã": ["Sorriso", "Sinop"],
  "Nova Xavantina": ["Barra do Garças", "Barra do Garças"],
  "Novo Horizonte do Norte": ["Juara", "Sinop"],
  "Novo Mundo": ["Peixoto de Azevedo - Guarantã do Norte", "Sinop"],
  "Novo Santo Antônio": ["Confresa - Vila Rica", "Barra do Garças"],
  "Novo São Joaquim": ["Barra do Garças", "Barra do Garças"],
  Paranaíta: ["Alta Floresta", "Sinop"],
  Paranatinga: ["Primavera do Leste", "Rondonópolis"],
  "Pedra Preta": ["Rondonópolis", "Rondonópolis"],
  "Peixoto de Azevedo": ["Peixoto de Azevedo - Guarantã do Norte", "Sinop"],
  "Planalto da Serra": ["Cuiabá", "Cuiabá"],
  Poconé: ["Cuiabá", "Cuiabá"],
  "Pontal do Araguaia": ["Barra do Garças", "Barra do Garças"],
  "Ponte Branca": ["Barra do Garças", "Barra do Garças"],
  "Pontes e Lacerda": ["Pontes e Lacerda - Comodoro", "Cáceres"],
  "Porto Alegre do Norte": ["Confresa - Vila Rica", "Barra do Garças"],
  "Porto dos Gaúchos": ["Juara", "Sinop"],
  "Porto Esperidião": ["Mirassol D'oeste", "Cáceres"],
  "Porto Estrela": ["Tangará da Serra", "Cuiabá"],
  Poxoréu: ["Primavera do Leste", "Rondonópolis"],
  "Primavera do Leste": ["Primavera do Leste", "Rondonópolis"],
  Querência: ["Água Boa", "Barra do Garças"],
  "Reserva do Cabaçal": ["Mirassol D'oeste", "Cáceres"],
  "Ribeirão Cascalheira": ["Água Boa", "Barra do Garças"],
  Ribeirãozinho: ["Barra do Garças", "Barra do Garças"],
  "Rio Branco": ["Cáceres", "Cáceres"],
  Rondolândia: ["Juína", "Sinop"],
  Rondonópolis: ["Rondonópolis", "Rondonópolis"],
  "Rosário Oeste": ["Cuiabá", "Cuiabá"],
  "Salto do Céu": ["Cáceres", "Cáceres"],
  "Santa Carmem": ["Sinop", "Sinop"],
  "Santa Cruz do Xingu": ["Confresa - Vila Rica", "Barra do Garças"],
  "Santa Rita do Trivelato": ["Sorriso", "Sinop"],
  "Santa Terezinha": ["Confresa - Vila Rica", "Barra do Garças"],
  "Santo Afonso": ["Diamantino", "Cuiabá"],
  "Santo Antônio de Leverger": ["Cuiabá", "Cuiabá"],
  "Santo Antônio do Leste": ["Primavera do Leste", "Rondonópolis"],
  "São Félix do Araguaia": ["Confresa - Vila Rica", "Barra do Garças"],
  "São José do Povo": ["Rondonópolis", "Rondonópolis"],
  "São José do Rio Claro": ["Diamantino", "Cuiabá"],
  "São José do Xingu": ["Confresa - Vila Rica", "Barra do Garças"],
  "São José dos Quatro Marcos": ["Mirassol D'oeste", "Cáceres"],
  "São Pedro da Cipa": ["Jaciara", "Rondonópolis"],
  Sapezal: ["Tangará da Serra", "Cuiabá"],
  "Serra Nova Dourada": ["Confresa - Vila Rica", "Barra do Garças"],
  Sinop: ["Sinop", "Sinop"],
  Sorriso: ["Sorriso", "Sinop"],
  Tabaporã: ["Juara", "Sinop"],
  "Tangará da Serra": ["Tangará da Serra", "Cuiabá"],
  Tapurah: ["Sorriso", "Sinop"],
  "Terra Nova do Norte": ["Sinop", "Sinop"],
  Tesouro: ["Rondonópolis", "Rondonópolis"],
  Torixoréu: ["Barra do Garças", "Barra do Garças"],
  "União do Sul": ["Sinop", "Sinop"],
  "Vale de São Domingos": ["Pontes e Lacerda - Comodoro", "Cáceres"],
  "Várzea Grande": ["Cuiabá", "Cuiabá"],
  Vera: ["Sorriso", "Sinop"],
  "Vila Bela da Santíssima Trindade": [
    "Pontes e Lacerda - Comodoro",
    "Cáceres",
  ],
  "Vila Rica": ["Confresa - Vila Rica", "Barra do Garças"],
};
